# loss functions

## nn.L1Loss

In [1]:
# abs(x-y)

import torch
import torch.nn as nn

loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 0.7534, -0.1731,  0.1325,  0.2065,  0.3034],
        [-0.1740,  0.3238,  0.2850,  1.1424, -0.0704],
        [ 1.3477,  1.8392, -0.7806,  0.8189, -0.3312]], requires_grad=True)
tensor([[ 8.4685e-01,  9.6426e-01,  8.0701e-01,  8.5679e-01, -1.8519e+00],
        [-6.7585e-02,  8.0516e-01,  4.0986e-01,  6.8410e-01,  1.5802e-01],
        [ 8.0661e-02,  9.3178e-01, -8.8218e-04, -1.2905e+00,  1.3687e+00]])
0.8582481741905212


## nn.MSELoss

In [2]:
# (x-y)^2

import torch
import torch.nn as nn

loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 0.2958, -0.9233, -1.9021, -0.7092, -0.1041],
        [ 0.0703, -2.0200, -0.3570,  0.5052, -0.5056],
        [ 0.0750, -0.6503,  1.7519,  1.6972, -0.0665]], requires_grad=True)
tensor([[-0.9058,  0.3344,  0.0975, -0.0076, -0.3049],
        [-0.6327,  0.5815, -0.9631,  0.8829, -0.5160],
        [-0.9373, -0.3831,  0.0127,  0.5185,  0.4145]])
1.4047034978866577


## nn.CrossEntropyLoss

In [3]:
# C개 아이템을 classify할 때 사용
# input은 (N, C), target은 (N), output은 scalar (N)
# 즉 input중 가장 높은 확률인 아이템이 몇번째인가?가 target이고 그에 따른 loss를 계산한다.

import torch
import torch.nn as nn

loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 2.6404, -0.5595,  1.5712, -0.7404, -0.3460],
        [ 0.4078,  0.1587,  1.1099,  0.2901, -1.6301],
        [-0.6836,  0.0432, -0.4229, -1.9503, -0.5072]], requires_grad=True)
tensor([3, 3, 2])
2.3197033405303955


## nn.CTCLoss

In [4]:
import torch
import torch.nn as nn

# Target are to be padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch (padding length)
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

 # Target are to be un-padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)

# Initialize random batch of targets (0 = blank, 1:C = classes)
target_lengths = torch.randint(low=1, high=T, size=(N,), dtype=torch.long)
target = torch.randint(low=1, high=C, size=(sum(target_lengths),), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

tensor([[[-1.6833, -3.8143, -4.5293,  ..., -2.8930, -2.0758, -2.6512],
         [-4.6271, -4.5812, -3.7796,  ..., -4.5686, -3.3960, -2.5119],
         [-3.3016, -2.2695, -3.1001,  ..., -2.0367, -3.1311, -2.7979],
         ...,
         [-3.4544, -3.1003, -4.3823,  ..., -3.0772, -3.2770, -3.7642],
         [-3.8873, -3.3922, -4.5446,  ..., -3.7278, -5.0861, -1.8861],
         [-3.4677, -2.0565, -2.5602,  ..., -4.0908, -3.4269, -3.8847]],

        [[-4.6454, -3.6305, -4.1969,  ..., -5.2624, -1.3588, -3.7721],
         [-4.1852, -3.3255, -3.5140,  ..., -0.9328, -4.0168, -2.9479],
         [-4.3201, -3.4748, -4.5620,  ..., -4.4836, -3.1178, -2.3926],
         ...,
         [-3.3245, -4.3286, -4.0611,  ..., -4.4482, -1.8963, -3.6606],
         [-4.3245, -3.7111, -3.3877,  ..., -3.3352, -3.6976, -2.6628],
         [-5.9423, -2.4370, -5.7293,  ..., -4.0399, -4.3442, -4.7280]],

        [[-3.7995, -3.2606, -2.6505,  ..., -3.9543, -3.3024, -3.8139],
         [-4.3025, -3.5650, -1.3846,  ..., -2

## nn.NLLLoss

In [5]:
import torch
import torch.nn as nn

m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()

# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss = nn.NLLLoss()
# input is of size N x C x height x width
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
m = nn.LogSoftmax(dim=1)
# each element in target has to have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
output = loss(m(conv(data)), target)
output.backward()
print(input)
print(target)
print(output.item())

tensor([[-0.4355,  0.9404, -0.1609, -0.5867, -0.9732],
        [-0.3017, -1.3037, -1.0465,  0.6768,  2.6003],
        [ 0.1424, -0.4455,  0.1418,  0.3988, -0.0615]], requires_grad=True)
tensor([[[0, 0, 2, 0, 1, 1, 0, 3],
         [3, 0, 0, 0, 2, 3, 1, 0],
         [0, 1, 1, 1, 2, 2, 0, 1],
         [2, 3, 1, 2, 0, 1, 0, 0],
         [0, 1, 0, 0, 0, 3, 1, 3],
         [0, 1, 0, 1, 2, 2, 0, 1],
         [1, 0, 1, 2, 3, 2, 3, 1],
         [0, 0, 0, 2, 1, 1, 0, 2]],

        [[2, 0, 2, 1, 1, 1, 1, 1],
         [2, 2, 3, 1, 3, 2, 0, 1],
         [2, 1, 3, 2, 0, 1, 1, 1],
         [1, 1, 3, 2, 2, 0, 0, 3],
         [1, 3, 2, 0, 3, 0, 1, 1],
         [2, 3, 3, 2, 2, 0, 3, 2],
         [2, 1, 1, 3, 3, 3, 1, 1],
         [3, 0, 0, 0, 3, 3, 2, 1]],

        [[1, 1, 0, 2, 1, 1, 0, 1],
         [1, 1, 2, 3, 2, 1, 1, 1],
         [2, 1, 1, 1, 1, 2, 2, 2],
         [2, 3, 3, 3, 0, 0, 1, 3],
         [1, 0, 1, 1, 1, 3, 0, 0],
         [1, 1, 2, 2, 3, 3, 0, 1],
         [2, 3, 1, 1, 3, 0, 2, 2],
     

## nn.PoissonNLLLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.KLDivLoss

## nn.BCELoss

In [ ]:
# 분류가 두가지인 경우 사용

import torch
import torch.nn as nn

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.BCEWithLogitsLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.BCEWithLogitsLoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.MarginRankingLoss

## nn.HingeEmbeddingLoss

## nn.MultiLabelMarginLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.MultiLabelMarginLoss()
x = torch.FloatTensor([[0.1, 0.2, 0.4, 0.8]])
# for target y, only consider labels 3 and 0, not after label -1
y = torch.LongTensor([[3, 0, -1, 1]])
output = loss(x, y)
print(x)
print(y)
print(output.item())

## nn.SmoothL1Loss

## nn.SoftMarginLoss

## nn.MultiLabelSoftMarginLoss

## nn.CosineEmbeddingLoss

## nn.MultiMarginLoss

## nn.TripletMarginLoss

In [ ]:
import torch
import torch.nn as nn

triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
anchor = torch.randn(100, 128, requires_grad=True)
positive = torch.randn(100, 128, requires_grad=True)
negative = torch.randn(100, 128, requires_grad=True)
output = triplet_loss(anchor, positive, negative)
output.backward()
print(input)
print(target)
print(output.item())